### ISSUE TITLE
Add Apis

### ISSUE THREAD

**Issue by piyushthapa** [maestro-org/haskell-sdk#2]
- [x] Account
- [x] Address
- [x] Assets
- [x] Epochs
- [x] General
- [x] Pool
- [x] Transactions

**Comment by 4TT1L4** [comment]
@sourabhxyz is this done or still pending?

I noticed that all the subtasks are marked as done, but the issue is still open since April 2023.

**Comment by sourabhxyz** [comment]
We can close this as relevant issues related to API improvements are already opened in separate issues. Thanks @4TT1L4!
